version: '3.1'

services:

  # TODO: evaluate potential alternative at first sign of conflict with front-end assets

  # storage switched to anonymous and/or docker volumes
  # mysql database
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: CMSDev
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # - ./data/db:/var/lib/mysql
      - db:/var/lib/mysql

  # phpmyadmin web interface
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:81
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

  # other data storage: redis, memcached, etc...



  # # CMS/Front-End apps
  # # wordpress cms
  # wordpress:
  #   image: wordpress:latest
  #   restart: always
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: exampleuser
  #     WORDPRESS_DB_PASSWORD: examplepass
  #     WORDPRESS_DB_NAME: CMSDev
  #   volumes:
  #     - ./data/app/wordpress:/var/www/html
  #     # - wordpress:/var/www/html


  # # drupal
  drupal:
    image: drupal
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
      ## Use of the following mapped directories results in container errors on attempted install
      # - ./data/app/drupal/modules:/var/www/html/modules:rwx
      # - ./data/app/drupal/profiles:/var/www/html/profiles:rw
      # - ./data/app/drupal/themes:/var/www/html/themes:rw
      # - ./data/app/drupal/sites:/var/www/html/sites:rw


volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  db:

#   wordpress:
