version: '3.1'

services:

  # TODO: evaluate potential alternative at first sign of conflict with front-end assets

  # storage switched to anonymous and/or docker volumes
  # mysql database
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: CMSDev
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # - ./data/db:/var/lib/mysql
      - db:/var/lib/mysql

  # # ugh, postgres too...
  # db:
  #   environment:
  #     POSTGRES_DB: CMSDev
  #     POSTGRES_USER: exampleuser
  #     POSTGRES_PASSWORD: examplepass
  #   restart: always
  #   image: postgres
  #   expose:
  #     - "5432"

  # phpmyadmin web interface
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:81
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

  # other data storage: redis, memcached, etc...

  # redis:
  #   restart: always
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   # expose:
  #   #   - "6379"

  # # CMS/Front-End apps
  # # PHP
  # # wordpress cms
  # wordpress:
  #   image: wordpress:latest
  #   restart: always
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: exampleuser
  #     WORDPRESS_DB_PASSWORD: examplepass
  #     WORDPRESS_DB_NAME: CMSDev
  #   volumes:
  #     - ./data/app/wordpress:/var/www/html
  #     # - wordpress:/var/www/html


  # # # drupal
  # drupal:
  #   image: drupal
  #   restart: always
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db
  #   volumes:
  #     - drupal-modules:/var/www/html/modules
  #     - drupal-profiles:/var/www/html/profiles
  #     - drupal-themes:/var/www/html/themes
  #     - drupal-sites:/var/www/html/sites
  #     ## Use of the following mapped directories results in container errors on attempted install
  #     # - ./data/app/drupal/modules:/var/www/html/modules:rwx
  #     # - ./data/app/drupal/profiles:/var/www/html/profiles:rw
  #     # - ./data/app/drupal/themes:/var/www/html/themes:rw
  #     # - ./data/app/drupal/sites:/var/www/html/sites:rw


  # # # Csharp
  # # # ORCHARD
  # orchardapp:
  #   image: orchardproject/orchardcore-cms-linux:latest
  #   container_name: orchardcms
  #   volumes:
  #     - ./data/app/orchardstore:/app/App_Data
  #   # links:
  #   #   - db:db
  #   #   - redis:redis
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - 5003:80

  # # Javascript/Node
  # # WikiJs
  wiki:
    image: ghcr.io/requarks/wiki:2   # they suggest using a specific major version; not :latest
    container_name: wiki
    restart: always
    depends_on:
      - db
    ports:
      - 80:3000
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: exampleuser
      DB_PASS: examplepass
      DB_NAME: CMSDev


  # # # PYTHON - HOLD; a bit more involved setup, run, build process
  # # # wagtail
  # app:
  #   environment:
  #     DJANGO_SECRET_KEY: changeme
  #     # DATABASE_URL: mysql://exampleuser:examplepass@db/CMSDev
  #     DATABASE_URL: postgres://exampleuser:examplepass@db/CMSDev
  #     CACHE_URL: redis://redis
  #   build:
  #     context: ./src/wagtailapp
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - wagtail-app:/app/demo/media
  #   #   # - app-data:/source/bakerydemo/media
  #   # # links:
  #   # #   - db:db
  #   # #   - redis:redis
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - db
  #     - redis


volumes:
  # database section
  db:

  # # wagtail section
  # wagtail-app:

  # # drupal section
  # drupal-modules:
  # drupal-profiles:
  # drupal-themes:
  # drupal-sites:

  # # wordpress section
#   wordpress:
