version: '3.1'

services:

  # TODO: evaluate potential alternative at first sign of conflict with front-end assets
  # mysql database
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: CMSDev
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/db:/var/lib/mysql
      # - db:/var/lib/mysql

  # phpmyadmin web interface
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:81
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

  # wordpress cms
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: CMSDev
    volumes:
      - ./data/wordpress:/var/www/html
      # - wordpress:/var/www/html

# volumes:
#   wordpress:
#   db:
